name: Build and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          check-latest: true

      - name: Cache Node.js modules and Eleventy build cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ hashFiles('eleventy.config.mjs') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site

    permissions:
      contents: write
